[package]
name = "rust_filesystem"
version = "0.1.0"
edition = "2021"


[dependencies]
tauri = "1.0"
fuzzy-matcher = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossterm = "0.26"
